# Creating spin and phonon operators

In [1]:
from pySDF import *
import numpy as np

/home/nikhil/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


pySDF is built to work with qutip and there are two classes for spin operators and states respectively. This allows for easy creating of spin states. We will first start by defining the number of spins/ions.

# Spin Operators

In [3]:
nSpins = 2
spinOperators = SpinOperators(nSpins)
spinStates = SpinStates(nSpins)

One of the most used spin operators is $\sigma_{\phi}^i$, where we have $\sigma_{\theta}^i = \mathcal{I}\otimes \mathcal{I} \otimes \cdots \sigma_{\phi} \otimes \cdots \otimes \mathcal{I}$ i.e. Identity everywhere except the ith spin. Here $\sigma_{\phi} = \cos(\phi)\sigma_x + \sin(\phi)\sigma_y  $. <br>
This is easily created using the following command:

In [5]:
i=1; theta=0
spinOperators.sigmaPhi(theta,i)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

As expected this is simply

In [8]:
qt.tensor([qt.qeye(2),qt.sigmax()])

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [10]:
spinOperators.X()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]

In [11]:
qt.tensor([qt.sigmax(),qt.sigmax()])

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

Similarly there are several other operators available and more information can be obtained in the API referrence. The SpinOperators class makes it easy to define highly used spin operators quickly.

# Spin States
Just like the spin operators, there are also some useful functions for easy generation of spin states. For example 

# Phonon Operators

In [ ]:

nOscillators = 3; oscDim=3 # number of states for truncating the Hilbert space
